service: nephele
app: nephele
org: georgelim

provider:
  name: aws
  runtime: python3.8
  logRetentionInDays: 14
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 1
  ecr:
    images:
      latest:
        path: "."
  versionFunctions: false
  environment:
    TELEGRAM_INTERFACE_NAME: ${self:custom.telegram.interfaceName}
    TELEGRAM_REQUEST_BASE_URL: ${self:custom.telegram.requestBaseUrl}
    USERS_TABLE_NAME: !Ref usersTable
  resourcePolicy:
    - ${file(resources/telegram/execute_api/webhook_resource_policy.yml)}

functions:
  epicGamesLogIn: ${file(resources/epic_games/functions/log_in.yml)}
  epicGamesListOffers: ${file(resources/epic_games/functions/list_offers.yml)}
  epicGamesPurchaseOffers: ${file(resources/epic_games/functions/purchase_offers.yml)}
  epicGamesLogOut: ${file(resources/epic_games/functions/log_out.yml)}
  eventsPutEvent: ${file(resources/events/functions/put_event.yml)}
  eventsListEvents: ${file(resources/events/functions/list_events.yml)}
  eventsEnableEvent: ${file(resources/events/functions/enable_event.yml)}
  eventsDisableEvent: ${file(resources/events/functions/disable_event.yml)}
  eventsDeleteEvent: ${file(resources/events/functions/delete_event.yml)}
  kijijiLogIn: ${file(resources/kijiji/functions/log_in.yml)}
  kijijiUploadAds: ${file(resources/kijiji/functions/upload_ads.yml)}
  kijijiDownloadAds: ${file(resources/kijiji/functions/download_ads.yml)}
  kijijiRepostAds: ${file(resources/kijiji/functions/repost_ads.yml)}
  kijijiDeleteAds: ${file(resources/kijiji/functions/delete_ads.yml)}
  kijijiLogOut: ${file(resources/kijiji/functions/log_out.yml)}
  textnowLogIn: ${file(resources/textnow/functions/log_in.yml)}
  textnowSendTextMessage: ${file(resources/textnow/functions/send_text_message.yml)}
  textnowLogOut: ${file(resources/textnow/functions/log_out.yml)}
  replyMessage: ${file(resources/core/functions/reply_message.yml)}

configValidationMode: error

resources:
  - ${file(resources/core/dynamodb/users_table.yml)}
  - ${file(resources/events/iam/execute_request_role.yml)}
  - ${file(resources/kijiji/s3/kijiji_ad_archive_bucket.yml)}

plugins:
  - serverless-export-outputs
  - serverless-iam-roles-per-function
  - serverless-plugin-scripts
  - serverless-step-functions

custom:
  core: ${file(resources/core/constants.yml)}
  epicGames: ${file(resources/epic_games/constants.yml)}
  events: ${file(resources/events/constants.yml)}
  kijiji: ${file(resources/kijiji/constants.yml)}
  telegram: ${file(resources/telegram/constants.yml)}
  textnow: ${file(resources/textnow/constants.yml)}
  exportOutputs:
    include:
      - ServiceEndpoint
      - TelegramBotApiToken: ${self:custom.telegram.botApiToken}
      - TelegramSetWebhookUrl: ${self:custom.telegram.requestBaseUrl}/setWebhook
      - TelegramWebhookPath: ${self:custom.telegram.webhookPath}
    output:
      file: ./.serverless/serverless_outputs.json
      format: json
  serverless-iam-roles-per-function:
    defaultInherit: true
  scripts:
    hooks:
      deploy:finalize: |
        python3 scripts/telegram/set_webhook.py \
          ${self:custom.exportOutputs.output.file}

stepFunctions:
  stateMachines:
    coreRequest: ${file(resources/core/state_machines/request.yml)}
    telegramRequest: ${file(resources/telegram/state_machines/request.yml)}
