service: nephele
app: nephele
org: georgelim

provider:
  name: aws
  runtime: python3.8
  logRetentionInDays: 14
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 1
  versionFunctions: false
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource: execute-api:/*/POST/webhook
        Condition:
          IpAddress:
            aws:SourceIp:
              - 149.154.160.0/20
              - 91.108.4.0/22
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:DescribeRule
            - events:ListTargetsByRule
            - events:PutRule
            - events:PutTargets
            - events:DeleteRule
            - events:RemoveTargets
          Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/*
  tracing:
    apiGateway: false
    lambda: false
  logs:
    restApi: false

package:
  patterns:
    - "!*"
    - "*.py"

functions:
  webhook:
    handler: nephele/webhook.handler
    memorySize: 10240
    timeout: 900
    environment:
      eventsTargetArn: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-webhook
      telegramBotApiUrl: https://api.telegram.org/bot${param:telegramBotApiToken}
    maximumRetryAttempts: 0
    events:
      - http:
          path: webhook
          method: POST
          async: true
          request:
            template:
              application/json: |
                #set($text = $input.path("$.message.text"))
                #set($chatId = $input.path("$.message.chat.id"))

                #if($!{text} == "")
                  #set($text = $input.path("$.edited_message.text"))
                  #set($chatId = $input.path("$.edited_message.chat.id"))
                #end

                #set($text = $text.replaceAll("“|”", '\"'))
                #set($text = $text.replaceAll("‘|’", "'"))
                #set($text = $text.replaceAll('\\', '\\\\'))
                #set($text = $text.replaceAll('\f', '\\f'))
                #set($text = $text.replaceAll('\n', '\\n'))
                #set($text = $text.replaceAll('\r', '\\r'))
                #set($text = $text.replaceAll('\t', '\\t'))
                #set($text = $text.replaceAll('\"', '\\\"'))

                {
                  "text": "$text",
                  "chatId": "$chatId",
                  "namespace": "${self:service}-${sls:stage}-$chatId"
                }

resources:
  Resources:
    WebhookLambdaPermissionEvents:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt WebhookLambdaFunction.Arn
        Principal: events.amazonaws.com
        Action: lambda:InvokeFunction
        SourceArn: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/*

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    pythonBin: python3
    staticCacheMaxVersions: 2
